### ISSUE TITLE
Control Keys feature not working

### ISSUE THREAD

**Issue by compmix** [mxrlkn/mouselock#7]
My understanding is that the "control keys" should be set to the same keybinds as ping and emotes and possibly others.

I have typed "g,t" into the field but it does not appear to be working.

https://github.com/mxrlkn/mouselock/blob/224477ed07ecaf243cbe3fba6a3250c8381ee21f/src/mouselockApp.swift#L67
From testing it seems that the controlkey variable is never true.

**Comment by mxrlkn** [comment]
Remember to give mouselock accessibility permissions. click the little text under the field. It should open the privacy settings.

**Comment by compmix** [comment]
Yes, it is enabled. Also rebooted as well.

Screenshot:
![image](https://user-images.githubusercontent.com/882908/184411144-ac0bcc14-ce01-4c73-9bae-0aea2914c518.png)

**Comment by mxrlkn** [comment]
Are you sure it's not working? If it doesn't work, your mouse should fly around when you hold down the key for quick pings or the emote wheel while you move your mouse. If you can use quick pings and the emote wheel fine, then it's working.

**Comment by compmix** [comment]
That’s correct, the mouse flies around everywhere when trying to ping. Is there any info I can send that would help you?

**Comment by mxrlkn** [comment]
Does the rest of the app work? does it keep your mouse within the window properly?

**Comment by compmix** [comment]
Yes, the rest of the app works. No problem either for League of Legends
only or for all windows. It just doesn't seem to deactivate when holding
the control keys.

**Comment by mxrlkn** [comment]
Okay then I'm not really sure what the issue is. Here's a few things that I think it could be:

- In a terminal, try to run `tccutil reset Accessibility mxrlkn.mouselock`. that will completely reset permissions. Try to enable permissions again. They can be a bit finicky. After you add it to permissions, close and reopen app. restarting your mac shouldn't do anything.
- I've only tested the app on MacOS 12.* Maybe it doesn't work on all MacOS versions.
- Maybe you have a weird keyboard/drivers that doesn't work with this? try another keyboard maybe.
- Maybe you have other apps running that catch keyboard events that messes with this app.
- Try and completely uninstall it with [AppCleaner](https://freemacsoft.net/appcleaner) and reinstall. Reset permissions first.

Also you don't need to open League to test this. just set it to Always active, and if the mouse shortly stops while you hold a control key while moving your mouse, it works correctly.

**Comment by compmix** [comment]
Thank you! The first step seems to have worked for me.

"In a terminal, try to run tccutil reset Accessibility mxrlkn.mouselock. that will completely reset permissions. Try to enable permissions again. They can be a bit finicky. After you add it to permissions, close and reopen app. restarting your mac shouldn't do anything."
